### ISSUE TITLE
google-fluentd constantly uses CPU, even when nothing is happening

### ISSUE THREAD

**Issue by erikdubbelboer** [GoogleCloudPlatform/fluent-plugin-google-cloud#167] opened 2017-10-12 07:20 UTC
When installing google-fluentd on a brand new GCE Ubuntu 16 LTE VM it immediately start using 1% CPU and always continues using around 1% CPU. Even if there is nothing at all happening on the system. This this behavior intended? Shouldn't it just drop to 0%?

We have a stackdriver Basic account if that changes anything.

Installed using:
```
curl -O https://dl.google.com/cloudagents/install-logging-agent.sh
sudo bash install-logging-agent.sh
```

Doing an strace shows:
```
$ sudo strace -p 2903
strace: Process 2903 attached
restart_syscall(<... resuming interrupted futex ...>) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 685, {200, 586359065}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 687, {200, 886693164}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 689, {201, 187052779}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 691, {201, 487444402}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 693, {201, 787887127}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 695, {202, 88296984}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 697, {202, 388643605}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fb911c1c0b4, FUTEX_WAIT_BITSET_PRIVATE, 699, {202, 689035134}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fb911c1c128, FUTEX_WAKE_PRIVATE, 1) = 0
...
```

**Comment by GLStephen** [comment] 2017-10-24 17:30
@rikdubbelboer FluentD is unlikely to go completely idle due to it's buffer monitoring at a minimum. It's likely polling the target resources, and a thread will always be active monitoring the buffer, so it's unlikely to drop to 0.

**Comment by erikdubbelboer** [comment] 2017-10-25 11:55
@GLStephen Why does FluentD need to poll anything? Can't it just use something like inotify?

1% all the time is a lot even for polling. I'm actually really surprised that no-one else has an issue with this seeing as everyone is affected.

**Comment by rjcrystal** [comment] 2018-01-20 04:54
@erikdubbelboer i am getting unusually high CPU usage with fluentd 

![screenshot at 2018-01-20 10-13-37](https://user-images.githubusercontent.com/1962366/35179968-a5cdaa3e-fdcb-11e7-8b47-cc524c46bb28.png)

**Comment by adg** [comment] 2018-01-21 22:32
I am also seeing this. A google_fluentd process spawning a ton of threads, using 100-200% CPU (as reported by top), and allocating memory until it is OOM killed by the kernel. If I kill it manually it just restarts and resumes its little dance.

**Comment by danielcompton** [comment] 2018-01-22 08:27
@adg, @rjcrystal  what instance size are you using? I only saw this behaviour on g1-small's, not n1-standard1 instances.

**Comment by adg** [comment] 2018-01-22 11:12
@danielcompton n1-standard-4

**Comment by rjcrystal** [comment] 2018-01-23 12:01
@danielcompton i am using n1-standard-2 it seems to be resolved after upgrading to version google-fluentd 1.5.25-1

**Comment by qingling128** [comment] 2018-01-23 17:44
Yeah, google-fluentd `1.5.25` includes a performance fix to reuse RPC stubs https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/203. Please upgrade to see if that helps.

There was also some known server side delay on Jan 18 that might cause the agent to retry more frequently, which increased the CPU usage temporarily. The issue has been resolved though. To mitigate the impact in the future, you can set `retry_wait` to a bit longer (say 10s instead of 1s). Reference: https://docs.fluentd.org/v0.12/articles/buffer-plugin-overview#parameters.

As for the ~ 1% CPU usage when there is no logs, that is because Fluentd is checking logs and monitoring buffers as @GLStephen suggested. I'll run some benchmark to measure the idle resource usage.

**Comment by adg** [comment] 2018-01-23 20:33
@qingling128 It was a surprise to me that I was running google_fluentd at all, and so it was even more surprising to see it using 100% CPU in top (and getting instance over-utilization warnings from the Cloud Console). If there is a configuration option to improve this, I don't know where to set it; I didn't install google-fluentd. Any improved config value should be the default for the google-fluentd installed on Compute VMs.

> There was also some known server side delay on Jan 18 that might cause the agent to retry more frequently, which increased the CPU usage temporarily. The issue has been resolved though.

When you say the issue is resolved, do you mean in the client or server?

**Comment by qingling128** [comment] 2018-01-26 06:25
@adg - Sorry for the delay. Was traveling this week and catching up with emails now.

Which environment are you in? GCE standard VMs do not have google_fluentd installed by default. Google-optimized VM images might have built-in google_fluentd though. So are GAE Flex or GKE customers. The way to custom configurations differ in those environment. Please let us know so we could provider better suggestions.

BTW, We are putting in a lot of efforts this quarter and the next to characterize and improve performance of Logging Agent. We are also looking to offer options to set hard bound of resource (CPU/memory) usage of the agent.

As for the `retry_limit` and related settings, the main concern against disabling retrying forever or setting the `retry_limit` longer by default is that we will sacrifice with some log loss and latency. We are revisiting the default configuration though to see what the best balance is and how to handle server side outage more gracefully.

As to the issue on Jan 18, the resolution was on the server side. But we've added a ticket to our road map to prevent this from the client side as well.

**Comment by qingling128** [comment] 2018-02-07 22:33
PR https://github.com/GoogleCloudPlatform/google-fluentd/pull/74 has been submitted to enforce retry limit by default and let users opt in forever retries if needed.

**Comment by kardianos** [comment] 2019-07-11 18:37
I'm also surprised by this. I have a simple container running directly on a COS image on GCE. My container is built in Go and hardly moves the CPU when not in use. The `google-fluentd` process (and the ruby runtime) take up 35% of my CPU, when the system is completely idle otherwise.

Can this process/container be re-written in C or Go?

**Comment by igorpeshansky** [comment] 2019-07-11 19:47
It's not really about Ruby. COS is not well supported by the logging agent. The version it uses is actually fairly old, as I recall. We will work with the COS team to update it.

**Comment by cakrit** [comment] 2019-07-24 10:22
I really don't get what this software is trying to do. I disabled all log ingestion as shown below, when I noticed the 3.69 TiB of data ingested:

![Screenshot from 2019-07-24 12-10-36](https://user-images.githubusercontent.com/43294513/61785843-d2bdb780-ae0c-11e9-8bb2-89edf85713c1.png)

The fluentd's container cpu usage fell for about an hour from the constant high cpu usage (around 90% of the container's limits), only to suddenly start its old tricks again, with no apparent reason:

![Screenshot from 2019-07-24 12-12-13](https://user-images.githubusercontent.com/43294513/61786067-42cc3d80-ae0d-11e9-8fed-00b5f0225dc4.png)

Any ideas on what might be going on? I was running with `1.12.7-gke.25`, upgrading now to the latest, to see if it will make a difference.

**Comment by cakrit** [comment] 2019-07-24 12:11
Things look much better after the upgrade to `1.13.7-gke.8`. Still seeing some relatively constant CPU usage (as others have already reported) and surprisingly large memory usage, but it's really nothing compared to what I was seeing before. It's been running as shown below for a couple of hours. My hypothesis is that disabling logging via the cloud console didn't quite work before and that the upgrade resulted in a clean slate.

![Screenshot from 2019-07-24 14-00-19](https://user-images.githubusercontent.com/43294513/61792205-76fb2a80-ae1c-11e9-964f-d7606dd95bb5.png)

**Comment by kardianos** [comment] 2019-07-25 02:36
@cakrit Thank you for looking into this. The CPU in the graphs do look much improved.

The memory graph is still comparatively high just to ship logs. For any node size smaller then an n1-standard, f1 or g1, this amount of memory is still significant to ship logs. Maybe I'll write something up that watches the container and machine logs and pushes them up to stackdriver.

**Comment by cakrit** [comment] 2019-07-25 06:55
Thanks @kardianos, but my main point is that the state you see in the last charts is *without* shipping any logs, except for what can't be disabled via the Google cloud console. Logging is disabled as you see in https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/167#issuecomment-514574350

**Comment by igorpeshansky** [comment] 2019-07-25 12:45
@cakrit, how exactly did you disable log ingestion? The logging agent on COS should ingest logs against the GCE instance resource. Looks like there are some log exclusions set up for that resource, but log exclusions don't prevent the agent from sending the logs — exclusions are processed on the server when the logs are received.
You can look at the log ingestion rate for a specific monitored resource by using the logging.googleapis.com/byte_count metric in Stackdriver. If you filter by instance id, you should then see exactly how much log volume is sent from your instance. logging.googleapis.com/excluded_byte_count will show how much you're sending but filtering out on the server (again, per resource).

**Comment by cakrit** [comment] 2019-07-25 15:21
I disabled them just via Stackdriver logging -> Logs ingestion, essentially what you see in the screenshot. 

I clicked on Stackdriver monitoring multiple times, to look for the metrics you mentioned, but I keep getting a DEADLINE_EXCEEDED error that I'm not going to be able to look into. Is there perhaps a `/metrics` endpoint or something else I could possibly access directly, without relying on Google console for the metrics?

I understand what you said about sending/receiving, but then the drop from 90% CPU usage to "reasonable" levels can be attributed just to the upgrade.

**Comment by igorpeshansky** [comment] 2019-07-25 15:59
If you've used the "Disable log source" pulldown menu item, you've only set up a [logs exclusion](https://cloud.google.com/logging/docs/exclusions) in your project. That means the API will drop those logs if they are ever sent to it. Your agent is still sending logs.

The metric I referenced (logging.googleapis.com/excluded_byte_count) will show you how much data is being sent and dropped. Because that metric comes from the logging API, it is only present (and thus accessible) in Stackdriver, not locally in your cluster.

If the [Stackdriver UI](https://app.google.stackdriver.com) is not working for you, you should be able to access those metrics directly via the [Stackdriver Monitoring API](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list) (that page has a "Try this API" section where you can construct your own REST request). That will get you the raw point values, but you really only need the latest one for the measurement I'm suggesting above.

We've been making improvements to both the logging agent code and the associated COS configs, so yes, it's possible that an upgrade caused the agent resource usage to stabilize.

**Comment by cakrit** [comment] 2019-07-25 16:41
Not a very user-friendly API :)
It's fine though, what you've said makes sense.

**Comment by igorpeshansky** [comment] 2019-07-25 17:28
The API was never intended to be queried by human users directly — that's what the UI is for. :-) I simply suggested the API as a workaround for your UI issues. I do encourage you to file feedback from the UI on the DEADLINE_EXCEEDED errors, or send email to google-stackdriver-discussion@googlegroups.com about them, rather than suffering silently (or grumbling).

**Comment by qingling128** [comment] 2019-08-02 21:50
Mystery solved. Closing this.

**Closed by qingling128** 2019-08-02 21:50 UTC
