### ISSUE TITLE
Logrotate causes causes tail to stop until manual service restart

### ISSUE THREAD

**Issue by mbennett-zendesk** [GoogleCloudPlatform/fluent-plugin-google-cloud#270] opened 2018-12-07 00:56 UTC
Occasionally, during logrotate on a GCE CentOS 7 VM, fluentd does not restart correctly, and logs are not tailed until the service is restarted. Using stock configuration of google-fluentd. 

Added a `sudo systemctl restart google-fluentd` to the `postrotate` block in the google-fluentd logrotate config. Still saw the same issue. Any help appreciated ASAP - this is causing Stackdriver logging to stop on the platform entirely unless it is manually checked daily.

**Comment by jkohen** [comment] 2019-07-31 15:24
@qingling128 you've investigated logrotate issues. Could you look into this one as well?

**Comment by igorpeshansky** [comment] 2019-08-05 21:54
This is a duplicate of GoogleCloudPlatform/google-fluentd#142.

**Closed by igorpeshansky** 2019-08-05 21:54 UTC
Labels: p1, question
