### ISSUE TITLE
Plugin fails with td-agent on RHEL 7.3

### ISSUE THREAD

**Issue by evmin** [GoogleCloudPlatform/fluent-plugin-google-cloud#112] opened 2017-01-18 01:10 UTC
Getting the following output:

2017-01-18 12:09:04 +1100 [info]: Worker 0 finished unexpectedly with status 127
2017-01-18 12:09:04 +1100 [info]: reading config file path="./td-agent.conf"
2017-01-18 12:09:04 +1100 [info]: starting fluentd-0.14.11 without supervision pid=6763
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-cloudwatch-logs' version '0.3.5'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-google-cloud' version '0.5.3'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-kafka' version '0.4.1'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-mongo' version '0.7.16'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-s3' version '0.8.0'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-systemd' version '0.1.0'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-td' version '0.10.29'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2017-01-18 12:09:04 +1100 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2017-01-18 12:09:04 +1100 [info]: gem 'fluentd' version '0.14.11'
2017-01-18 12:09:04 +1100 [info]: gem 'fluentd' version '0.12.31'
2017-01-18 12:09:04 +1100 [info]: adding match pattern="scg.**" type="google_cloud"
^C2017-01-18 12:09:04 +1100 [info]: Received graceful stop
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:3: warning: already initialized constant JSON::VERSION
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:3: warning: previous definition of VERSION was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION_ARRAY
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_MAJOR
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MINOR
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_BUILD
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:99: warning: already initialized constant JSON::NaN
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:99: warning: previous definition of NaN was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:101: warning: already initialized constant JSON::Infinity
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:101: warning: previous definition of Infinity was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:103: warning: already initialized constant JSON::MinusInfinity
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:103: warning: previous definition of MinusInfinity was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:128: warning: already initialized constant JSON::UnparserError
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:128: warning: previous definition of UnparserError was here
/opt/td-agent/embedded/bin/ruby: symbol lookup error: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/google-protobuf-3.0.2-x86_64-linux/lib/google/protobuf_c.so: undefined symbol: rb_data_typed_object_wrap

**Comment by igorpeshansky** [comment] 2017-01-18 01:14
We are working to address the issue. In the meantime, please explicitly install 0.5.2, which should work.

**Comment by igorpeshansky** [comment] 2017-01-18 16:39
Duplicate of #106.

**Closed by igorpeshansky** 2017-01-18 16:39 UTC
