### ISSUE TITLE
Support specifying 'message_key' for text payload, 'severity_key' for severity, and 'time_key' for the timestamp

### ISSUE THREAD

**Issue by mr-salty** [GoogleCloudPlatform/fluent-plugin-google-cloud#4] opened 2015-04-16 21:02 UTC
this is based on @filipjs comment on #3 

  About format none:
  """The key field is “message” by default, but you can specify a different value using the message_key parameter as shown below"""
  is it possible to read that 'message_key' in the plugin and use it here instead of hard-coding 'message'?

I noted that other output plugins support this (see http://docs.fluentd.org/articles/out_file) so we should as well.

**Comment by mr-salty** [comment] 2015-09-09 22:38
We should also allow specifying the field name for 'severity'.

**Comment by mr-salty** [comment] 2016-09-08 17:19
We should also add keep_severity_key, etc. - analogous to keep_time_key for http://docs.fluentd.org/articles/in_tail

**Comment by tonglil** [comment] 2017-07-07 15:49
Is there a way to also specify the key for JSON log messages?
The log driver I use formats the json log message key as `msg` instead of `message`, and I don't really have a way to transform that.

This is in addition to the severity key.

Overall, there should either be some transformers available in SD logging to format log fields into native SD fields better, or SD logging should make it easier to parse logs (like Papertrail).

**Comment by igorpeshansky** [comment] 2017-07-07 18:07
There are transformers available: http://docs.fluentd.org/articles/filter_record_transformer. However, in some environments (e.g., GKE) users don't have access to the logging agent configuration, so they can't use these.

**Comment by tonglil** [comment] 2017-07-08 00:51
Yes, this is a GKE environment. 

Ideally these transformers can be applied and adjusted in stackdriver as well.

**Comment by igorpeshansky** [comment] 2017-07-08 02:12
Unfortunately, this is not possible on GKE today. This is a limitation of the GKE configuration. It's possible to override it by deploying the whole logging subsystem yourself, but there are caveats.
I believe one workaround is to output your logs to a file and run a sidecar container to transform them into the correct form and dump them to stdout. @crassirostris and @piosz may have more recommendations.

**Comment by crassirostris** [comment] 2017-07-08 21:30
@tonglil GKE eng here. The problem is, we in GKE want to make it work as smoothly as possible and maintain the logging infrastructure for you. When there's a bug in the agent or a new Kubernetes version requires a new way of scraping logs, we fix it for you. If GKE configuration is allowed to be changed, it's not clear how to maintain it on GKE side, i.e update the image or configuration without breaking changes, introduced by users. It would be strange for example if each update would swipe out all the changes you made last time.

It's possible to opt out of GKE taking care of your configuration, fixing bug and updating the image, it's described in the [Kubernetes docs](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver#configuring-stackdriver-logging-agents). Then you can arbitrary change the fluentd configuration, including adding the sections to transform the records.

If there's some progress on making it possible to have both the ability for GKE to maintain core functionality and the ability for users to make config changes, you'll hear about it :)

/cc @fgrzadkowski

**Comment by igorpeshansky** [comment] 2017-08-28 14:52
@tonglil FYI, #146 adds `msg` as a supported key for environments where JSON is detected (including GKE). It will be checked by default, with no extra configuration needed.

**Comment by igorpeshansky** [comment] 2018-02-13 23:34
Also `time_key`.

**Comment by qingling128** [comment] 2018-08-23 18:33
Just a side note, there are [a couple of existing Fluentd plugins](https://cloud.google.com/logging/docs/agent/configuration#modifying_log_records) we can use to rename fields in the log.

An example use case can be found here: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml#L102

**Comment by jkohen** [comment] 2019-07-31 20:25
@qingling128  Is there any action left in this issue?

**Comment by qingling128** [comment] 2019-08-02 22:00
Yes, we have not yet implemented this feature.

**Comment by jkohen** [comment] 2019-08-05 13:34
@qingling128  Do we still need it? It was filed over 4 years ago.

**Comment by qingling128** [comment] 2019-08-05 15:52
We discussed about adding and switching these field names to be prefixed with `logging.googleapis.com` for consistency as the [other fields](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L144). It can only be done in a major release though. We have an internal tracker for this in the major release cut doc.

**Comment by toniree** [comment] 2019-10-01 00:10
This also happens (log level not being captured) for Google Compute Engine running Docker images. Is the fluentd configuration the way to go in my case as well?

**Comment by qingling128** [comment] 2019-10-03 01:41
@toniree Yes, that's the workaround for now.

**Comment by nesl247** [comment] 2020-04-14 14:07
Is there an update on this? Logging should not be such a horrendous experience on GKE.

**Comment by qingling128** [comment] 2024-08-12 16:35
Closing this as obsolete since GCE has moved to Ops Agent, and GKE has moved to Fluent Bit. Both support these features.

**Closed by qingling128** 2024-08-12 16:35 UTC
Labels: enhancement
