### ISSUE TITLE
Configurable severity key

### ISSUE THREAD

**Issue by dominikschulz** [GoogleCloudPlatform/fluent-plugin-google-cloud#125] opened 2017-04-21 13:19 UTC
Please support changing the key where the severity field is read from.

Currently it seems to be hardcoded to `severity` at https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L913.

Our logging libs mostly use a field called `level` and it would be very hard, if not impossible, to change them all.

**Comment by igorpeshansky** [comment] 2017-04-21 13:32
This is a duplicate of https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/4.
You can use the [record_transformer](http://docs.fluentd.org/v0.14/articles/filter_record_transformer) filter as a workaround.

**Closed by igorpeshansky** 2017-04-21 13:32 UTC

**Comment by dominikschulz** [comment] 2017-04-21 13:37
Sorry, wasn't obvious from reading the issue subjects.

Thanks!

**Comment by igorpeshansky** [comment] 2017-04-21 14:03
Thanks for pointing that out. Fixed.

**Comment by tonglil** [comment] 2017-06-22 16:31
Is there a way to do this in GKE (add a transformer)?

**Comment by qingling128** [comment] 2017-06-22 17:38
For GKE, right now we support extracting severity from fields with name`severity` or `stream`. Similarly, you should be able to use [record_transformer](http://docs.fluentd.org/v0.14/articles/filter_record_transformer) filter if you are logging `severity` in a field with a different name.

**Comment by igorpeshansky** [comment] 2017-06-22 17:55
The logging agent configuration on GKE is not really accessible to users. The only way to override severity is by writing JSON records, one per line, that will be parsed into structured logs. The severity will be determined by the "severity" key in those records.

**Comment by dominikschulz** [comment] 2017-06-22 19:07
Writing JSON record with the severity/level in the field `severity` works well for our own applications, but most third-party applications use either `level` or something entirely different for their loglevel field. Thus it would be really great if GKE customers had a way of changing this.
