### ISSUE TITLE
Use on non-GCP non-AWS systems

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/fluent-plugin-google-cloud#156] opened 2017-08-31 18:02 UTC
Are non-GCP non-AWS systems supported by this plugin? Since Stackdriver APIs can be used from anywhere, this plugin should work from anywhere/any platform. Also, please document how to configure and use it on other platforms where metadata server/zone/vm_id etc are not applicable.
Thanks.

**Comment by qingling128** [comment] 2017-08-31 18:13
Hi @meta-coder, unfortunately we don't yet support non-GCP and non-AWS systems as of today. It is on our roadmap though. We don't have a specific timeline yet, but it's on our radar.

**Comment by igorpeshansky** [comment] 2017-08-31 21:38
To expand on what @qingling128 said, the plugin does a bit more than call the API -- it also embeds the logic to detect where it's running or where the data is coming from, so that users don't have to supply that information. This logic has not yet been adapted to non-GCP and non-AWS platforms.

**Comment by Azuka** [comment] 2017-11-22 04:31
Just wanted to show interest in this as well. I'm building out a service that would benefit from forwarding logs to Stackdriver for monitoring.

**Comment by zacman85** [comment] 2017-12-04 23:06
+1 from my team as well. We use cloud logging from inside our data center and would love to have a more standardized, maintained approach using this fluentd plugin.

**Comment by qingling128** [comment] 2017-12-04 23:26
Thanks all for showing the interest and helping us prioritize our tasks! We've added a note in the agenda for tomorrow's Logging Agent product sync meeting to re-emphasize the impact / interest from customers on this feature. Stay tuned. :)

**Comment by bakkerpeter** [comment] 2017-12-06 14:48
Also makes sense, for us at least, to be able to use this in a Minikube environment.

**Comment by mjkelly** [comment] 2017-12-06 17:47
This was the first option I looked into for a bare-metal kubernetes installation we are planning to use for some prod traffic. I would have used it if it was supported.

**Comment by bakkerpeter** [comment] 2017-12-06 18:35
@igorpeshansky Thanks for pointing that out. I got the project id working, indeed by loading the credentials file. I also tried to figure out how to change the configMap but since I'm to far from understanding the Fluent config, it felt like trail and error. 
Could you give me a short sample? Thanks a lot.

**Comment by igorpeshansky** [comment] 2017-12-06 18:41
In the fluentd config, right after `@type google_cloud`, add:
```
  vm_id MY_VM_ID
  zone MY_ZONE
```
The [instructions](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/#configuring-stackdriver-logging-agents) I pointed to for changing the Kubernetes ConfigMap should tell you how to get to that bit of configuration.

**Comment by derekperkins** [comment] 2017-12-28 12:44
@igorpeshansky After following your instructions to manually set the `vm_id` and `zone`, fluentd got further along and actually started, but then kicked out an error, presumably on flush. Is this something that can be easily changed/overridden?

```
2017-12-28 12:34:18 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-12-28 12:34:48 +0000 error_class="Signet::AuthorizationError" error="Authorization failed.  Server message:\n{\n \"error\": \"invalid_scope\",\n \"error_description\": \"Invalid downscoping, scopes should not be specified as a request parameter.\"\n}" plugin_id="object:3fba9d778d40"
```

**Comment by igorpeshansky** [comment] 2017-12-28 14:02
This was caused by #179, which was rolled back in #198. You should bump the plugin version to `0.6.12`.

**Comment by derekperkins** [comment] 2017-12-28 16:08
Thanks for the clarification. I was just using gcr.io/google-containers/fluentd-gcp:2.0.11, which must have shipped with 0.6.11. I rolled my image back to gcr.io/google-containers/fluentd-gcp:2.0.10 and it started working. Thanks!

**Comment by mlushpenko** [comment] 2018-05-26 17:31
Hi, any update on this? Spent few hours trying to set up monitoring with stackdriver only to figure out it is not working for on-prem environments :)

**Comment by sarmadali20** [comment] 2018-08-21 15:45
@mactr0n is this for minikube or vmware k8s cluster I am getting the following in the logging-agent pod 

```
2018-08-21T15:44:32.717051457Z 2018-08-21 15:44:32 +0000 [error]: Failed to access metadata service:  error=#&lt;Net::OpenTimeout: execution expired&gt;
2018-08-21T15:44:32.717083776Z 2018-08-21 15:44:32 +0000 [info]: Unable to determine platform
2018-08-21T15:44:32.721066461Z 2018-08-21 15:44:32 +0000 [error]: config error file="/etc/google-fluentd/google-fluentd.conf" error="Unable to obtain metadata parameters: zone vm_id"
2018-08-21T15:44:32.725580067Z 2018-08-21 15:44:32 +0000 [info]: process finished code=256
2018-08-21T15:44:32.725642498Z 2018-08-21 15:44:32 +0000 [error]: fluentd main process died unexpectedly. restarting.
```

**Comment by mactr0n** [comment] 2018-08-22 06:46
@sarmadali20 we use it on a custom (kubeamd) and aks cluster. Could you please post the complete config?
It seems as if you forget to disable the metadata agent:
```    
      enable_metadata_agent false
```

**Comment by duanshiqiang** [comment] 2018-09-16 02:56
Would like to see this plugin working on any environment.

**Comment by srabenhorst** [comment] 2018-09-16 07:01
@duanshiqiang just follow my hints and it will work anywhere. We use the plugin for log forwarding on a custom cluster and azure.

**Comment by bryanlarsen** [comment] 2018-11-29 16:45
Steps to running stackdriver logging on non Kubernetes environments outside of GCE or AWS:

First get it running on a GCE instance so you can compare against something that acutally works.

1. Create  a service account and put creds in /etc/google/auth/application_default_credentials.json 
2. Follow installation steps from https://cloud.google.com/logging/docs/agent/installation
3. edit /etc/google-fluentd/google-fluentd.conf and add after `@type google_cloud`

    project_id XXX
    vm_id my-machine-name
    zone northamerica-northeast1-b

4. sudo systemctl restart google-fluentd
5. look for your logs under "GCE VM Instance", my-machine-name

**Comment by caarlos0** [comment] 2018-12-21 15:17
@bryanlarsen suggestion works, thanks!

**Comment by AlexandreProenca** [comment] 2019-05-28 18:43
@bryanlarsen works for me, thanks!.

**Comment by jkohen** [comment] 2019-07-30 21:17
I'm glad you found a solution that works for you. I'll close this ticket because the plugin meets our design goals.

**Closed by jkohen** 2019-07-30 21:17 UTC
Labels: enhancement

**Comment by adamlukaszczyk** [comment] 2019-08-10 21:39
@jkohen Could you mention in the Documentation about this configuration changes suggested by @bryanlarsen. It will help a lot others ;) 👍

**Comment by luckoseabraham** [comment] 2019-08-20 18:37
I have a PKS cluster and I have followed the above steps and the logs are coming in the stackdriver under the GCE Compute section.
Are there additional steps needed to push these logs to kubernetes cluster group ?
